apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-consumer-service
  namespace: app-system
spec:
  ports:
  - port: 9002
    targetPort: 9002
    protocol: TCP
  selector:
    app: rabbitmq-consumer
  type: LoadBalancer
